### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by adborden** [DataShades/ckanext-saml2#111]
The last release was 0.3.0 in June 2017. There have been 28 commits since then on link-master. I'm trying to upgrade, but not sure if I should be using 0.3.0 or link-master. If link-master is stable, then maybe we can publish a new release?

**Comment by Engerrs** [comment]
Hi @adborden , thank you for mentioning that. We updated the version of the link-master branch and created a tag for the new version.

**Comment by adborden** [comment]
Thanks
