### ISSUE TITLE
Define the maintainer of this code

### ISSUE THREAD

**Issue by avdata99** [DataShades/ckanext-saml2#114]
We are [looking for ckanex-saml2 mantainer](https://github.com/GSA/datagov-deploy/issues/1401).

We have 2 candidates as upstream: 
 - [This repo at 0.4 version](https://github.com/DataShades/ckanext-saml2/blob/link-master/CHANGES.md#040) (@Engerrs)
 - [The OKF 0.4 version](https://github.com/okfn/ckanext-saml2/blob/link-master/CHANGES.md#040) (@amercader)

**Both repos adds support from CKAN 2.8** (and fixed some issues) and have a doifferent 0.4 version.

Should we consider this repo as the official `ckanext-saml2` version?

**Comment by Engerrs** [comment]
Hi @avdata99 
Well this repository had to be the official one because https://github.com/GSA/ckanext-saml2 is not being supported by the original maintainer.
I actually didn't know that Adria had he's own fork from our repo.

**Comment by avdata99** [comment]
Thanks for the quick response @Engerrs 
As you said, @amercader create a new fork and also added support for CKAN 2.8 but not used this version. Maybe in the future we can merge or analyze both repos.
By now I'll consider this as a upstream and use it in our project. 
Thanks.
