### ISSUE TITLE
Entity ID

### ISSUE THREAD

**Issue by fpjr** [DataShades/ckanext-saml2#56]
I'm trying to look for a material that I can refer to know the "entityID" that this plugin creates. But I can't find anything yet. Are there any forums or mailing-lists that I can follow for this plugin? What I'm trying to accomplish is to create a configuration to use Salesforce's SAML IDP.

**Comment by MrkGrgsn** [comment]
The entity ID of the service provider is configured in `sp_config.py`, see the [example](https://github.com/DataShades/ckanext-saml2/blob/link-master/ckanext/saml2/config/sp_config.py#L12).

Most of the SAML2 configuration actually relates to the underlying SAML2 library, https://github.com/rohe/pysaml2, documentation for which is at http://pysaml2.readthedocs.io/en/latest/.  The doco is not that comprehensive however.

**Comment by fpjr** [comment]
This has been resolved a few weeks back. Thank you for the response anyway.
